#!/bin/sh
set -e

SRCDIR=$(dirname $(realpath $0))
cd $ADTTMP
g++ -Wall -Werror -pedantic -Wno-long-long -fPIC -o poppler-qt5-test $SRCDIR/test-qt5.cpp `pkg-config --cflags --libs poppler-qt5 Qt5Core`
./poppler-qt5-test "/usr/share/cups/data/default-testpage.pdf"
